version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python /app/manage.py wait_for_db && 
             python /app/manage.py makemigrations && 
             python /app/manage.py migrate && 
             python /app/manage.py collectstatic --noinput && 
             cp -r /app/static/* /vol/web/static && 
             gunicorn --workers=2 --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./backend:/app
      - /Users/apple/100DayPython/RecipeDjangoBackendFrontend/vol/web:/vol/web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
