name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: app_db
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: app_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r backend/requirements.txt
          pip install -r backend/requirements.dev.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          python backend/manage.py test

      - name: Build Docker image
        run: |
          docker build -t recipe-django-backend:latest -f backend/Dockerfile .

      - name: Save Docker image to tarball
        run: |
          docker save recipe-django-backend:latest > recipe-django-backend.tar

      - name: Upload Docker image to GitHub Actions artifacts
        uses: actions/upload-artifact@v2
        with:
          name: recipe-django-backend-image
          path: recipe-django-backend.tar
